version: '3'
services:
  qlub-7-days-to-die:
    container_name: qlub-7-days-to-die
    build:
      context: .
    ports:
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "9090:8080"
      - "8081:8081"
    volumes:
      - 7-days-to-die:/7-days-to-die
    environment:
      - QLUB_SERVER_PASSWORD
volumes:
  7-days-to-die:
