version: '3'
services:
  qlub-7-days-to-die:
    container_name: qlub-7-days-to-die
    build:
      context: .
    ports:
      - "26900:26900/tcp"
      - "26900-26903:26900-26903/udp"
      # - "9090:8080"
      - "8081:8081"
    volumes:
      - 7-days-to-die:/7-days-to-die
    environment:
      - QLUB_SERVER_PASSWORD
  discord-notify-bot:
    image: ruby
    entrypoint: ["ruby", "/app/discord_notify_bot.rb"]
    volumes:
      - .:/app
      - 7-days-to-die:/7-days-to-die
    environment:
      - DISCORD_WEBHOOK_URL
volumes:
  7-days-to-die:
